# Form implementation generated from reading ui file 'atualizaraluno.ui'
#
# Created by: PyQt6 UI code generator 6.7.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets
from PyQt6.QtWidgets import QMessageBox

import mariadb
conexao = mariadb.connect(host="localhost", user="root", password="", database="escola")
cursor = conexao.cursor()
print("Conectado.")

class Ui_AtualizarAluno(object):
    def setupUi(self, AtualizarAluno):
        AtualizarAluno.setObjectName("AtualizarAluno")
        AtualizarAluno.resize(321, 253)
        self.centralwidget = QtWidgets.QWidget(parent=AtualizarAluno)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout.setObjectName("gridLayout")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label_codigo = QtWidgets.QLabel(parent=self.centralwidget)
        self.label_codigo.setObjectName("label_codigo")
        self.horizontalLayout.addWidget(self.label_codigo)
        self.lineEdit_codigo = QtWidgets.QLineEdit(parent=self.centralwidget)
        self.lineEdit_codigo.setObjectName("lineEdit_codigo")
        self.horizontalLayout.addWidget(self.lineEdit_codigo)
        self.pushButton_abrir = QtWidgets.QPushButton(parent=self.centralwidget)
        self.pushButton_abrir.setObjectName("pushButton_abrir")

        self.pushButton_abrir.clicked.connect(self.abrir)

        self.horizontalLayout.addWidget(self.pushButton_abrir)
        self.gridLayout.addLayout(self.horizontalLayout, 0, 0, 1, 1)
        self.gridLayout_2 = QtWidgets.QGridLayout()
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.checkBox_atleta = QtWidgets.QCheckBox(parent=self.centralwidget)
        self.checkBox_atleta.setObjectName("checkBox_atleta")
        self.horizontalLayout_3.addWidget(self.checkBox_atleta)
        self.checkBox_bolsista = QtWidgets.QCheckBox(parent=self.centralwidget)
        self.checkBox_bolsista.setObjectName("checkBox_bolsista")
        self.horizontalLayout_3.addWidget(self.checkBox_bolsista)
        self.gridLayout_2.addLayout(self.horizontalLayout_3, 3, 1, 1, 1)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.radioButton_manha = QtWidgets.QRadioButton(parent=self.centralwidget)
        self.radioButton_manha.setObjectName("radioButton_manha")
        self.horizontalLayout_2.addWidget(self.radioButton_manha)
        self.radioButton_tarde = QtWidgets.QRadioButton(parent=self.centralwidget)
        self.radioButton_tarde.setObjectName("radioButton_tarde")
        self.horizontalLayout_2.addWidget(self.radioButton_tarde)
        self.radioButton_noite = QtWidgets.QRadioButton(parent=self.centralwidget)
        self.radioButton_noite.setObjectName("radioButton_noite")
        self.horizontalLayout_2.addWidget(self.radioButton_noite)
        self.gridLayout_2.addLayout(self.horizontalLayout_2, 2, 1, 1, 1)
        self.plainTextEdit_obs = QtWidgets.QPlainTextEdit(parent=self.centralwidget)
        self.plainTextEdit_obs.setObjectName("plainTextEdit_obs")
        self.gridLayout_2.addWidget(self.plainTextEdit_obs, 4, 1, 1, 1)
        self.label_nome = QtWidgets.QLabel(parent=self.centralwidget)
        self.label_nome.setObjectName("label_nome")
        self.gridLayout_2.addWidget(self.label_nome, 0, 0, 1, 1)
        self.label_curso = QtWidgets.QLabel(parent=self.centralwidget)
        self.label_curso.setObjectName("label_curso")
        self.gridLayout_2.addWidget(self.label_curso, 1, 0, 1, 1)
        self.label_turno = QtWidgets.QLabel(parent=self.centralwidget)
        self.label_turno.setObjectName("label_turno")
        self.gridLayout_2.addWidget(self.label_turno, 2, 0, 1, 1)
        self.lineEdit_nome = QtWidgets.QLineEdit(parent=self.centralwidget)
        self.lineEdit_nome.setObjectName("lineEdit_nome")
        self.gridLayout_2.addWidget(self.lineEdit_nome, 0, 1, 1, 1)
        self.label_obs = QtWidgets.QLabel(parent=self.centralwidget)
        self.label_obs.setObjectName("label_obs")
        self.gridLayout_2.addWidget(self.label_obs, 4, 0, 1, 1)
        self.label_extras = QtWidgets.QLabel(parent=self.centralwidget)
        self.label_extras.setObjectName("label_extras")
        self.gridLayout_2.addWidget(self.label_extras, 3, 0, 1, 1)
        self.comboBox_curso = QtWidgets.QComboBox(parent=self.centralwidget)
        self.comboBox_curso.setObjectName("comboBox_curso")
        self.comboBox_curso.addItem("")
        self.comboBox_curso.addItem("")
        self.comboBox_curso.addItem("")
        self.comboBox_curso.addItem("")
        self.gridLayout_2.addWidget(self.comboBox_curso, 1, 1, 1, 1)
        self.pushButton_atualizar = QtWidgets.QPushButton(parent=self.centralwidget)
        self.pushButton_atualizar.setObjectName("pushButton_atualizar")
        self.gridLayout_2.addWidget(self.pushButton_atualizar, 5, 1, 1, 1)
        self.gridLayout.addLayout(self.gridLayout_2, 1, 0, 1, 1)
        AtualizarAluno.setCentralWidget(self.centralwidget)

        self.retranslateUi(AtualizarAluno)
        QtCore.QMetaObject.connectSlotsByName(AtualizarAluno)

    def retranslateUi(self, AtualizarAluno):
        _translate = QtCore.QCoreApplication.translate
        AtualizarAluno.setWindowTitle(_translate("AtualizarAluno", "Atualizar Aluno"))
        self.label_codigo.setText(_translate("AtualizarAluno", "Código:"))
        self.pushButton_abrir.setText(_translate("AtualizarAluno", "Abrir"))
        self.checkBox_atleta.setText(_translate("AtualizarAluno", "Atleta"))
        self.checkBox_bolsista.setText(_translate("AtualizarAluno", "Bolsista"))
        self.radioButton_manha.setText(_translate("AtualizarAluno", "Manhã"))
        self.radioButton_tarde.setText(_translate("AtualizarAluno", "Tarde"))
        self.radioButton_noite.setText(_translate("AtualizarAluno", "Noite"))
        self.label_nome.setText(_translate("AtualizarAluno", "Nome:"))
        self.label_curso.setText(_translate("AtualizarAluno", "Curso:"))
        self.label_turno.setText(_translate("AtualizarAluno", "Turno:"))
        self.label_obs.setText(_translate("AtualizarAluno", "Obs:"))
        self.label_extras.setText(_translate("AtualizarAluno", "Extras:"))
        self.comboBox_curso.setItemText(0, _translate("AtualizarAluno", "Edificações"))
        self.comboBox_curso.setItemText(1, _translate("AtualizarAluno", "Eletrotécnica"))
        self.comboBox_curso.setItemText(2, _translate("AtualizarAluno", "Informática"))
        self.comboBox_curso.setItemText(3, _translate("AtualizarAluno", "Mecânica"))
        self.pushButton_atualizar.setText(_translate("AtualizarAluno", "Atualizar"))

    def abrir(self):
        codigo = self.lineEdit_codigo.text()
        sql = "SELECT * FROM aluno WHERE codigo = " + codigo
        cursor.execute(sql)
        dados = cursor.fetchall()

        if len(dados) == 0:
            print("REGISTRO NÃO ENCONTRADO")
        else:
            self.lineEdit_nome.setText(dados[0][1])
            self.comboBox_curso.setCurrentText(dados[0][2])

            if dados[0][3] == "Manhã":
                self.radioButton_manha.setChecked(True)
            elif dados[0][3] == "Tarde":
                self.radioButton_tarde.setChecked(True)
            elif dados[0][3] == "Noite":
                self.radioButton_noite.setChecked(True)
            
            if dados[0][4] == "Sim":
                self.checkBox_atleta.setChecked(True)
            else:
                self.checkBox_atleta.setChecked(False)
            
            if dados[0][5] == "Sim":
                self.checkBox_bolsista.setChecked(True)
            else:
                self.checkBox_bolsista.setChecked(False)
            
            self.plainTextEdit_obs.setPlainText(dados[0][6])




if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    AtualizarAluno = QtWidgets.QMainWindow()
    ui = Ui_AtualizarAluno()
    ui.setupUi(AtualizarAluno)
    AtualizarAluno.show()
    sys.exit(app.exec())
