# Form implementation generated from reading ui file 'login.ui'
#
# Created by: PyQt6 UI code generator 6.7.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets
from PyQt6.QtWidgets import QMessageBox


class Ui_Login(object):
    def setupUi(self, Login):
        Login.setObjectName("Login")
        Login.resize(203, 167)
        self.centralwidget = QtWidgets.QWidget(parent=Login)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setObjectName("verticalLayout")
        self.label_system = QtWidgets.QLabel(parent=self.centralwidget)
        self.label_system.setObjectName("label_system")
        self.verticalLayout.addWidget(self.label_system)
        self.label_usuario = QtWidgets.QLabel(parent=self.centralwidget)
        self.label_usuario.setObjectName("label_usuario")
        self.verticalLayout.addWidget(self.label_usuario)
        self.lineEdit_usuario = QtWidgets.QLineEdit(parent=self.centralwidget)
        self.lineEdit_usuario.setObjectName("lineEdit_usuario")
        self.verticalLayout.addWidget(self.lineEdit_usuario)
        self.label_senha = QtWidgets.QLabel(parent=self.centralwidget)
        self.label_senha.setObjectName("label_senha")
        self.verticalLayout.addWidget(self.label_senha)
        self.lineEdit_senha = QtWidgets.QLineEdit(parent=self.centralwidget)
        self.lineEdit_senha.setEchoMode(QtWidgets.QLineEdit.EchoMode.Password)
        self.lineEdit_senha.setObjectName("lineEdit_senha")
        self.verticalLayout.addWidget(self.lineEdit_senha)
        self.pushButton_entrar = QtWidgets.QPushButton(parent=self.centralwidget)
        self.pushButton_entrar.setObjectName("pushButton_entrar")
        
        self.pushButton_entrar.clicked.connect(self.entrar)
        
        self.verticalLayout.addWidget(self.pushButton_entrar)
        Login.setCentralWidget(self.centralwidget)

        self.retranslateUi(Login)
        QtCore.QMetaObject.connectSlotsByName(Login)

    def retranslateUi(self, Login):
        _translate = QtCore.QCoreApplication.translate
        Login.setWindowTitle(_translate("Login", "Acesso ao Sistema"))
        self.label_system.setText(_translate("Login", "SUPER SYSTEM 1.0"))
        self.label_usuario.setText(_translate("Login", "Usuário:"))
        self.label_senha.setText(_translate("Login", "Senha:"))
        self.pushButton_entrar.setText(_translate("Login", "ENTRAR"))


    def entrar(self):
        usuario = self.lineEdit_usuario.text()
        senha   = self.lineEdit_senha.text()
        
        if usuario == "admin" and senha == "legal":
            # importar a classe da tela que será aberta
            from menu import Ui_Menu
            # criar uma tela vazia
            self.tela = QtWidgets.QMainWindow()
            # criar um objeto com a tela que deseja abrir
            self.menu = Ui_Menu()
            # assiciar o objeto com a tela vazia
            self.menu.setupUi(self.tela)
            # exibir a tela
            self.tela.show()
            # fechar a janela de login
            Login.close()
            
        else:
            msg = QMessageBox()
            msg.setWindowTitle("Aviso")
            msg.setText("ACESSO NEGADO")
            msg.exec()
            



if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Login = QtWidgets.QMainWindow()
    ui = Ui_Login()
    ui.setupUi(Login)
    Login.show()
    sys.exit(app.exec())
