# Form implementation generated from reading ui file 'pesquisa.ui'
#
# Created by: PyQt6 UI code generator 6.7.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets

### CONECTAR AO BD ###################################################
import mariadb
conexao = mariadb.connect(host="localhost", user="root", 
                          password="", database="escola")
cursor = conexao.cursor()
print("Conexão OK.")
#####################################################################

class Ui_PesquisaAluno(object):
    def setupUi(self, PesquisaAluno):
        PesquisaAluno.setObjectName("PesquisaAluno")
        PesquisaAluno.resize(333, 277)
        self.centralwidget = QtWidgets.QWidget(parent=PesquisaAluno)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label_nome = QtWidgets.QLabel(parent=self.centralwidget)
        self.label_nome.setObjectName("label_nome")
        self.horizontalLayout.addWidget(self.label_nome)
        self.lineEdit_nome = QtWidgets.QLineEdit(parent=self.centralwidget)
        self.lineEdit_nome.setObjectName("lineEdit_nome")
        self.horizontalLayout.addWidget(self.lineEdit_nome)
        self.pushButton_pesquisar = QtWidgets.QPushButton(parent=self.centralwidget)
        self.pushButton_pesquisar.setObjectName("pushButton_pesquisar")
        
        self.pushButton_pesquisar.clicked.connect(self.pesquisar)
        
        self.horizontalLayout.addWidget(self.pushButton_pesquisar)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.plainTextEdit_dados = QtWidgets.QPlainTextEdit(parent=self.centralwidget)
        self.plainTextEdit_dados.setObjectName("plainTextEdit_dados")
        self.verticalLayout.addWidget(self.plainTextEdit_dados)
        PesquisaAluno.setCentralWidget(self.centralwidget)

        self.retranslateUi(PesquisaAluno)
        QtCore.QMetaObject.connectSlotsByName(PesquisaAluno)

    def retranslateUi(self, PesquisaAluno):
        _translate = QtCore.QCoreApplication.translate
        PesquisaAluno.setWindowTitle(_translate("PesquisaAluno", "Pesquisar Alunos"))
        self.label_nome.setText(_translate("PesquisaAluno", "Nome:"))
        self.pushButton_pesquisar.setText(_translate("PesquisaAluno", "Pesquisar"))


    def pesquisar(self):
        nome = self.lineEdit_nome.text()
        cursor.execute(f"SELECT * FROM aluno WHERE nome LIKE '%{nome}%' ")
        dados = cursor.fetchall()
        
        texto = ""
        for linha in dados:
            texto += "Código: " + str(linha[0]) + "\n"
            texto += "Nome: " + linha[1] + "\n"
            texto += "Curso: " + linha[2] + "\n\n"
        
        self.plainTextEdit_dados.setPlainText(texto)
        
        
if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    PesquisaAluno = QtWidgets.QMainWindow()
    ui = Ui_PesquisaAluno()
    ui.setupUi(PesquisaAluno)
    PesquisaAluno.show()
    sys.exit(app.exec())
