# Form implementation generated from reading ui file 'somador.ui'
#
# Created by: PyQt6 UI code generator 6.7.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_Janela(object):
    def setupUi(self, Janela):
        Janela.setObjectName("Janela")
        Janela.resize(279, 189)
        self.centralwidget = QtWidgets.QWidget(parent=Janela)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayoutWidget = QtWidgets.QWidget(parent=self.centralwidget)
        self.gridLayoutWidget.setGeometry(QtCore.QRect(10, 10, 261, 171))
        self.gridLayoutWidget.setObjectName("gridLayoutWidget")
        self.gridLayout = QtWidgets.QGridLayout(self.gridLayoutWidget)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setObjectName("gridLayout")
        self.lineEdit_v1 = QtWidgets.QLineEdit(parent=self.gridLayoutWidget)
        self.lineEdit_v1.setObjectName("lineEdit_v1")
        self.gridLayout.addWidget(self.lineEdit_v1, 0, 1, 1, 1)
        self.pushButton_somar = QtWidgets.QPushButton(parent=self.gridLayoutWidget)
        self.pushButton_somar.setObjectName("pushButton_somar")
        self.pushButton_somar.clicked.connect(self.somar)
        self.gridLayout.addWidget(self.pushButton_somar, 2, 1, 1, 1)
        self.label_v1 = QtWidgets.QLabel(parent=self.gridLayoutWidget)
        self.label_v1.setObjectName("label_v1")
        self.gridLayout.addWidget(self.label_v1, 0, 0, 1, 1)
        self.lineEdit_v2 = QtWidgets.QLineEdit(parent=self.gridLayoutWidget)
        self.lineEdit_v2.setObjectName("lineEdit_v2")
        self.gridLayout.addWidget(self.lineEdit_v2, 1, 1, 1, 1)
        self.label_v2 = QtWidgets.QLabel(parent=self.gridLayoutWidget)
        self.label_v2.setObjectName("label_v2")
        self.gridLayout.addWidget(self.label_v2, 1, 0, 1, 1)
        self.lineEdit_resultado = QtWidgets.QLineEdit(parent=self.gridLayoutWidget)
        self.lineEdit_resultado.setObjectName("lineEdit_resultado")
        self.gridLayout.addWidget(self.lineEdit_resultado, 3, 1, 1, 1)
        self.label_resultado = QtWidgets.QLabel(parent=self.gridLayoutWidget)
        self.label_resultado.setObjectName("label_resultado")
        self.gridLayout.addWidget(self.label_resultado, 3, 0, 1, 1)
        Janela.setCentralWidget(self.centralwidget)

        self.retranslateUi(Janela)
        QtCore.QMetaObject.connectSlotsByName(Janela)

    def retranslateUi(self, Janela):
        _translate = QtCore.QCoreApplication.translate
        Janela.setWindowTitle(_translate("Janela", "Somador"))
        self.pushButton_somar.setText(_translate("Janela", "SOMAR"))
        self.label_v1.setText(_translate("Janela", "Valor1:"))
        self.label_v2.setText(_translate("Janela", "Valor2:"))
        self.label_resultado.setText(_translate("Janela", "Resultado:"))
    
    def somar(self):
        v1 = int(self.lineEdit_v1.text())
        v2 = int(self.lineEdit_v2.text())
        resultado = v1 + v2
        self.lineEdit_resultado.setText(str(resultado))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Janela = QtWidgets.QMainWindow()
    ui = Ui_Janela()
    ui.setupUi(Janela)
    Janela.show()
    sys.exit(app.exec())
